spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springshop
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  activemq:
    broker-url: tcp://localhost:61616
    object-queue-name: storeQueue
    packages:
      trusted: shop.learnup.shop.domain.messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmail@user.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
auth:
  jwt:
    secret: "dlniknvJnksekjhBKVskhKFs"